### ISSUE TITLE
fail to start on arch linux

### ISSUE THREAD

**Issue by qLb** [mattallty/muguet#8]
```
sudo -E bash -c 'muguet setup'
~/.nvm/v4.5.0/lib/node_modules/muguet/lib/check-config.js:34
  var hasDockerExecutable = dockerCli.hasDockerExecutable()                                 ^

TypeError: Cannot read property 'hasDockerExecutable' of undefined
    at exports.setup (~/.nvm/v4.5.0/lib/node_modules/muguet/lib/check-config.js:34:38)
    at Cli.run (~/.nvm/v4.5.0/lib/node_modules/muguet/bin/cli.js:70:12)
    at Object.<anonymous> (~/.nvm/v4.5.0/lib/node_modules/muguet/bin/cli.js:145:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```
`Linux 4.8.7-1-ARCH #1 SMP PREEMPT Thu Nov 10 17:22:48 CET 2016 x86_64 GNU/Linux`

**Comment by qLb** [comment]
what v of nodejs binary should i use to build this?
